(function(f){if(typeof exports==="object"&&typeof module!=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof window!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{g=this}g.papillon = f()}})(function(){var define,module,exports;return (function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code="MODULE_NOT_FOUND",f}var l=n[o]={exports:{}};t[o][0].call(l.exports,function(e){var n=t[o][1][e];return s(n?n:e)},l,l.exports,e,t,n,r)}return n[o].exports}var i=typeof require=="function"&&require;for(var o=0;o<r.length;o++)s(r[o]);return s})({1:[function(require,module,exports){
"use strict";var _interopRequire=function(e){return e&&e.__esModule?e["default"]:e};Object.defineProperty(exports,"__esModule",{value:!0});var State=_interopRequire(require("./src/state")),Observer=_interopRequire(require("./src/observer"));exports.State=State,exports.Observer=Observer;


},{"./src/observer":2,"./src/state":3}],2:[function(require,module,exports){
"use strict";var _interopRequire=function(e){return e&&e.__esModule?e["default"]:e},_createClass=function(){function e(e,t){for(var r in t){var n=t[r];n.configurable=!0,n.value&&(n.writable=!0)}Object.defineProperties(e,t)}return function(t,r,n){return r&&e(t.prototype,r),n&&e(t,n),t}}(),_classCallCheck=function(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")},State=_interopRequire(require("./state")),Observer=function(){function e(t,r,n){var i=this;if(_classCallCheck(this,e),!t||!r||!n)throw new TypeError("Invalid arguments");this.host=t,this.callback=n,this.properties=[].concat(r).map(function(e){var t=Object.getOwnPropertyDescriptor(i.host,e);if(!t.configurable)throw new TypeError("'"+e+"': Configurable property required");return{property:e,descriptor:t}}),this.state=new State(this.properties.reduce(function(e,t){var r=t.property,n=t.descriptor,o=void 0,c=void 0;return e[r]=i.host[r],o=n.get?function(){return e[r]=n.get.call(i.host)}:function(){return e[r]},c=n.set?function(e){n.set.call(i.host,e),o()}:function(t){return e[r]=t},Object.defineProperty(i.host,r,{configurable:!0,enumerable:n.enumerable,get:function(){return i.check(),o()},set:function(e){c(e),i.check()}}),e},{}))}return _createClass(e,{check:{value:function(){var e=this;this.requestId||this.checking||(this.requestId=window.requestAnimationFrame(function(){e.checking=!0,e.state.isChanged()&&e.callback(e.state.changelog),e.checking=e.requestId=void 0}))}},destroy:{value:function(){var e=this;this.requestId&&window.cancelAnimationFrame(this.requestId),this.properties.forEach(function(t){var r=t.property,n=t.descriptor;n.get||n.set||(n.value=e.state.target[r]),Object.defineProperty(e.host,r,n)})}}}),e}();module.exports=Observer;


},{"./state":3}],3:[function(require,module,exports){
"use strict";var _createClass=function(){function e(e,t){for(var a in t){var n=t[a];n.configurable=!0,n.value&&(n.writable=!0)}Object.defineProperties(e,t)}return function(t,a,n){return a&&e(t.prototype,a),n&&e(t,n),t}}(),_classCallCheck=function(e,t){if(!(e instanceof t))throw new TypeError("Cannot call a class as a function")},map=new WeakMap,timestamp=0,request=!1,State=function(){function e(t){if(_classCallCheck(this,e),!e.isObject(t))throw new TypeError("Invalid arguments");var a=map.get(t);return a?a:(map.set(t,this),this.cache=Object.keys(t).reduce(function(a,n){var c=a[n]=t[n];return e.isObject(c)&&new e(c),a},{}),this.target=t,this.lastCheck=e.now(),void(this.lastChange=0))}return _createClass(e,{isChanged:{value:function(){var t=this,a=e.now();return a>this.lastCheck&&!function(){var n=!1;t.lastCheck=a,t.changelog={},Object.keys(t.cache).forEach(function(e){if(!t.target.hasOwnProperty(e)){var a=t.cache[e];t.changelog[e]={type:"delete",oldValue:a},n=!0}}),t.cache=Object.keys(t.target).reduce(function(a,c){var r=t.target[c];if(t.cache.hasOwnProperty(c)?e.is(r,t.cache[c])||(t.changelog[c]=t.changelog[c]||{type:"update"},t.changelog[c].oldValue=t.cache[c],n=!0):(t.changelog[c]={type:"add"},n=!0),e.isObject(r)){var o=new e(r);o.isChanged()&&(n=!0,t.changelog[c]||(t.changelog[c]={type:"modify"},t.changelog[c].changelog=o.changelog))}return a[c]=t.target[c],a},{}),n?t.lastChange=t.lastCheck:t.changelog=void 0}(),this.lastChange===a}}},{now:{value:function(){return request||(timestamp+=1,request=window.requestAnimationFrame(function(){return request=void 0})),timestamp}},isObject:{value:function(e){return"object"==typeof e&&null!==e}},is:{value:function(e,t){return 0===e&&0===t?1/e===1/t:e!==e?t!==t:e===t}}}),e}();module.exports=State;


},{}]},{},[1])(1)
});


//# sourceMappingURL=papillon-umd.js.map
